apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
          ports:
            - containerPort: 2016
          env:
            - name: MINIO_ROOT_USER
              value: "theship"
            - name: MINIO_ROOT_PASSWORD
              value: "theship1234"
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
spec:
  ports:
    - port: 2016
      targetPort: 9000
  externalIPs:
    - 192.168.100.15
  selector:
    app: minio
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi