apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":"2024-10-06T19:20:58Z","generation":3,"labels":{"app":"permastore","targetname":"permastore"},"name":"permastore","namespace":"theship-vendor","resourceVersion":"11055771","uid":"20ccc114-ed21-4c90-bf58-5c77cb2279ef"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"permastore"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"permastore"}},"spec":{"containers":[{"env":[{"name":"PYTHONUNBUFFERED","value":"1"},{"name":"K8S_HOST","value":"192.168.100.15"},{"name":"ENCRYPTION_KEY","value":"052734d35ce9067964d33e9ca0eed5019349d340"},{"name":"SIMULATION_HOST","value":"192.168.101.2"}],"image":"jzeladmin2006/m321-custom-permastore","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"initialDelaySeconds":120,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":2019},"timeoutSeconds":1},"name":"app","ports":[{"containerPort":2019,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"periodSeconds":2,"successThreshold":1,"tcpSocket":{"port":2019},"timeoutSeconds":1},"resources":{"limits":{"memory":"120M"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","enableServiceLinks":false,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-10-06T19:20:58Z","lastUpdateTime":"2024-10-16T18:05:09Z","message":"ReplicaSet \"permastore-6d9f9cbc7d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-10-22T09:25:38Z","lastUpdateTime":"2024-10-22T09:25:38Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":3,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-10-24T08:16:26Z"
  generation: 1
  labels:
    app: permastore
    targetname: permastore
  name: permastore
  namespace: theship-vendor
  resourceVersion: "1"
  uid: 78fb1efd-df82-432f-a8e6-c1dc79fbe47f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: permastore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: permastore
    spec:
      containers:
      - env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: K8S_HOST
          value: 192.168.100.15
        - name: ENCRYPTION_KEY
          value: 052734d35ce9067964d33e9ca0eed5019349d340
        - name: SIMULATION_HOST
          value: 192.168.101.2
        image: jzeladmin2006/m321-custom-permastore
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 2019
          timeoutSeconds: 1
        name: app
        ports:
        - containerPort: 2019
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 2019
          timeoutSeconds: 1
        resources:
          limits:
            memory: 120M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-10-24T08:16:36Z"
    lastUpdateTime: "2024-10-24T08:16:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-10-24T08:16:26Z"
    lastUpdateTime: "2024-10-24T08:16:36Z"
    message: ReplicaSet "permastore-6db767bdb4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-16T17:58:10Z"
  labels:
    targetname: permastore
  name: permastore
  namespace: theship-vendor
  resourceVersion: "10792741"
  uid: 4d9fffcb-1d7e-4c66-b169-dbf4c2d06ed2
spec:
  externalIPs:
    - 192.168.100.15
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-2019
      port: 2019
      protocol: TCP
      targetPort: 2019
  selector:
    app: permastore
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}